/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFunctionsClient } from "./IFunctionsClient";
export type { IFunctionsRouter } from "./IFunctionsRouter";
