/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFunctionsClient__factory } from "./IFunctionsClient__factory";
export { IFunctionsRouter__factory } from "./IFunctionsRouter__factory";
