/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../../../common";

export interface FunctionsRequestInterface extends utils.Interface {
  functions: {
    "REQUEST_DATA_VERSION()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "REQUEST_DATA_VERSION"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "REQUEST_DATA_VERSION",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "REQUEST_DATA_VERSION",
    data: BytesLike
  ): Result;

  events: {};
}

export interface FunctionsRequest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FunctionsRequestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    REQUEST_DATA_VERSION(overrides?: CallOverrides): Promise<[number]>;
  };

  REQUEST_DATA_VERSION(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    REQUEST_DATA_VERSION(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    REQUEST_DATA_VERSION(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    REQUEST_DATA_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
